version: '3.2'

services:
  postgres:
      image: postgres:10
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432:5432

  redis:
    image: redis:4
    ports:
        - 6379:6379
